//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace practiceChecking.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Table_1
    {
        [NotMapped]
        public int diff { get; set; }
        [NotMapped]
        public System.DateTime firsttime { get; set; }
        [NotMapped]
        public System.DateTime secondtime { get; set; }
    }
}
